// client/src/components/home.vue
<script>
import { ref, onMounted } from "vue";
import * as api from "../API/Api.js";

export default {
  name: "HomePanel",
  setup() {
    // Reactive variables for managing the state
    const links = ref([]);
    const newLink = ref('');
    const name = ref('');
   

   
    onMounted(() => {


      
      const token = localStorage.getItem('token');
      if (token) {
        api.fetchApplications(token)
          .then(response => {
            links.value = response.data;
          })
          .catch(error => console.error("Error fetching data:", error));
      }
    });

  

    
    const addLink = () => {
  if (newLink.value.trim()) {
    const token = localStorage.getItem('token');
    if (token) {
      api.addApplication(name.value, newLink.value, token)
        .then(() => {
          api.fetchApplications(token)
            .then(response => {
              links.value = response.data;
            })
            .catch(error => console.error("Error fetching updated data:", error));
          newLink.value = ''; // Reset input after adding link
        })
        .catch(error => console.error("Error adding link:", error));
    }
  }
};


    // Delete an application
    const deleteLink = (id) => {
      api.deleteApplication(id)
        .then(() => {
          const token = localStorage.getItem('token'); 
          api.fetchApplications(token)
            .then(response => {
              links.value = response.data;
            })
            .catch(error => console.error("Error fetching updated data:", error));
        })
        .catch(error => {
          console.error("Error deleting application:", error);
          alert("Failed to delete the application!");
        });
    };
        
    

    return {
      links,
      newLink,
      name,
      addLink,
      deleteLink,
    };
  },
};
</script>


<template>
 <v-container class="home" style="text-align: center; margin: 0px 50px 50px 50px; height: 100vh;">
  <v-row>
    <v-col cols="3">  
      <v-card class="pa-5 rounded-lg" elevation="5" color="grey-darken-4" >
              <v-card-title class="text-h5" style="text-align: center;">User Info</v-card-title>
              <v-card-text class="text-white">
                <p><strong>Name:</strong>Marek</p>
                <p><strong>Email:</strong> Franek</p>
          </v-card-text>
      </v-card>
    </v-col>
    <v-col cols="9">
    <h2 class="font-weight-black text-white ">Job Application Tracker</h2>
        <div class="d-flex justify-center mt-2">
          <v-card width="auto" color="grey-darken-4" class="white-glow">
            <v-card-text  class="text-h6 text-white">
              Total Applications: {{ links.length }}
            </v-card-text>
          </v-card>
        </div>
      <v-conatiner class="mx-10 align-center justify-center ">
        <v-row class="d-flex align-center justify-center">
              <v-col cols="4" class="pr-1">
                <v-text-field
                class="text-white"
                :rules="rules"
                v-model="name"
                hide-details="auto"
                label="Name of application"
                variant="outlined"
                rounded
                >
              </v-text-field>
            </v-col>
            <v-col cols="6" class="pl-1">
              <v-text-field
                class="text-white"
                v-model="newLink"
                :rules="rules"
                hide-details="auto"
                label="Enter application link"
                variant="outlined"
                rounded
                >
              </v-text-field>
            </v-col>
          </v-row>
          <v-btn variant="outlined" @click="addLink" color="white"  class="mt-5">Add Link</v-btn>
      </v-conatiner>
      
     
  
    
      <v-card  class="mx-auto my-8 custom-card"
              elevation="10"
              max-width="800" rounded="lg"
              color="grey-darken-4"
              >
        <v-table fixed-header class="custom-card" theme="grey-darken-4" hover = true >
              <thead>
                <tr>
                  <th class="text-left">
                    Id
                  </th>
                  <th class="text-center ">
                    Name
                  </th>
                  <th class="text-left">
                    Action
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="item in links" 
                  :key="item.id"
                >
                  <td class="text-left ">{{ item.id }}</td>
                  <td class="text-center "><a :href="item.link" target="_blank" rel="noopener noreferrer">{{ item.name }}</a></td>
                  <td class="text-left t"> <button @click="deleteLink(item.id)" style="margin-left: 10px;">Delete</button></td>
                </tr>
              </tbody>
            </v-table>
      </v-card>
    </v-col>
  </v-row>
 </v-container> 
  </template>
  
 
  
  <style >
body {
  background-color: #212121;
  color: #ffffff;
}
a {
  text-decoration: none;
  color: inherit;
}

a:visited {
  color: inherit;
}




  </style>

// react/src/views/home.js
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import * as api from '../Api';



const Home = () => {
    const [links, setLinks] = useState([]);
    const [newLink, setNewLink] = useState('');
    const [name, setName] = useState('');
    useEffect(() => {
        api.fetchAppplications()
            .then(response => setLinks(response.data))
            .catch(error => console.error('Error fetching data:', error));
    }, []);
    const addLink = () => {
        if (newLink.trim()) {
            api.addApplication(name, newLink)
                .then(() => {
                 api.fetchAppplications()
                        .then(response => setLinks(response.data))
                        .catch(error => console.error('Error fetching updated data:', error));
                    setNewLink('');
                })
                .catch(error => console.error('Error adding link:', error));
        }
    };
    const deleteLink = (id) => {
      api.deleteApplication(id)
            .then(() => {
                api.fetchAppplications()
                    .then(response => setLinks(response.data))
                    .catch(error => console.error('Error fetching updated data:', error));
            })
            .catch(error => {
                console.error('Error deleting application:', error);
                alert('Failed to delete the application!');
            });
    };
    return (
        <div style={{ textAlign: 'center', margin: '50px', height: '100vh' }}>
            <h1>Job Application Tracker</h1>
            <h2>Total Applications: {links.length}</h2>
            <input
                type="text"
                placeholder="Name of application"
                value={name}
                onChange={(e) => setName(e.target.value)}
                style={{ padding: '10px', width: '200px', marginRight: '2px' }}
            />
            <input
                type="text"
                placeholder="Enter application link"
                value={newLink}
                onChange={(e) => setNewLink(e.target.value)}
                style={{ padding: '10px', width: '300px' }}
            />
            <button onClick={addLink} style={{ marginLeft: '10px', padding: '10px' }}>
                Add Link
            </button>
            <ul style={{ marginTop: '20px', listStyle: 'none' }}>
                {links.map((item) => (
                    <li key={item.id}>
                        <a href={item.link} target="_blank" rel="noopener noreferrer">
                            {item.name}
                        </a>
                        <button onClick={() => deleteLink(item.id)} style={{ marginLeft: '10px' }}>
                            Delete
                        </button>
                    </li>
                ))}
            </ul>
        </div>
    );
};
export default Home;
